import "./App.css";

function HomePage() {
  return (
    <div className="min-h-screen bg-primary text-white">
      <div className="hidden">GENERATED BY CHATGPT 4</div>
      <header className="text-center py-8 border-b-2 border-ally">
        <h1 className="text-7xl uppercase font-black font-headline text-accent">
          Voter Bowl
        </h1>
        <p className="text-xl font-body uppercase text-ally">
          Where rivalry fuels democracy.
        </p>
      </header>

      <main className="flex flex-col items-center bg-black/25 justify-center">
        <section className="my-8">
          <h2 className="text-4xl font-bold uppercase text-accent text-center">
            This Week's Matchup
          </h2>
          <div className="flex justify-around items-center my-16">
            <div className="text-center p-4 bg-secondary rounded-lg">
              <h3 className="text-2xl font-bold text-rival">
                Villanova Wildcats
              </h3>
              <p className="font-body uppercase font-black text-5xl">
                202 regs
              </p>
            </div>

            <span className="text-4xl font-bold mx-2 text-gray-200">VS.</span>

            <div className="text-center p-4 bg-secondary rounded-lg">
              <h3 className="text-2xl font-bold text-ally">Temple Owls</h3>
              <p className="font-body font-black uppercase text-5xl">
                400 regs
              </p>
            </div>
          </div>
        </section>

        <div className="my-8">
          <a
            href="/register"
            className="bg-accent text-primary font-bold py-2 px-4 rounded hover:bg-orange-500 transition duration-150 ease-in-out"
          >
            Register to vote NOW!
          </a>
        </div>
      </main>
    </div>
  );
}

export default HomePage;
